package gohttp

import (
	"html/template"
	"log"
	"net/http"

	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

// EnableDocs mounts Swagger UI at /docs on the server's router.
// It serves the OpenAPI spec generated by swag init and renders
// an interactive Swagger UI for exploring the API.
//
// This should only be called when a --docs flag is set. Production
// deployments (Cloud Run) should NOT expose docs.
//
// The swaggerJSON parameter is the raw swagger.json content generated
// by swag init. Passing it directly avoids the need for each service
// to register a global spec via swag.Register — which requires an
// import side-effect and init() magic that doesn't compose well in
// a monorepo with multiple services.
func EnableDocs(r chi.Router, swaggerJSON []byte) {
	// Serve the raw spec at /docs/swagger.json so Swagger UI can fetch it.
	r.Get("/docs/swagger.json", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write(swaggerJSON) //nolint:errcheck
	})

	// Mount Swagger UI at /docs/*. The URL option points Swagger UI
	// at our /docs/swagger.json endpoint instead of the default
	// /swagger/doc.json path.
	r.Get("/docs/*", httpSwagger.Handler(
		httpSwagger.URL("/docs/swagger.json"),
	))

	// Redirect /docs to /docs/index.html for convenience.
	r.Get("/docs", http.RedirectHandler("/docs/index.html", http.StatusMovedPermanently).ServeHTTP)

	// Serve the aggregator index at /docs-all linking to all nexus
	// services. Useful for local dev where each service runs on a
	// different port.
	r.Get("/docs-all", DocsIndex(NexusServices))

	log.Println("[gohttp] Swagger UI enabled at /docs")
	log.Println("[gohttp] All-services index at /docs-all")
}

// NexusServices lists all nexus HTTP services and their local dev
// Swagger UI URLs. Used by the /docs-all aggregator page.
var NexusServices = []ServiceLink{
	{Name: "secrets", URL: "http://localhost:8081/docs", Description: "Count-based secret admission service"},
	{Name: "cal", URL: "http://localhost:8082/docs", Description: "Calendar/iCal service"},
	{Name: "portal", URL: "http://localhost:8090/docs", Description: "Web portal (auth, admin, dashboard)"},
	{Name: "vn", URL: "http://localhost:8080/docs", Description: "Visual novel engine"},
	{Name: "discord-monitor", URL: "http://localhost:8080/docs", Description: "Discord monitoring service"},
}

// DocsIndexPage returns an HTML page listing all nexus services with
// links to their Swagger UI endpoints. This is used by the aggregator
// endpoint to provide a single entry point for API exploration.
var docsIndexTmpl = template.Must(template.New("docs-index").Parse(`<!DOCTYPE html>
<html>
<head>
  <title>nexus API Documentation</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 600px; margin: 4em auto; padding: 0 1em; }
    h1 { font-size: 1.5em; }
    ul { list-style: none; padding: 0; }
    li { margin: 0.75em 0; }
    a { color: #0066cc; text-decoration: none; font-size: 1.1em; }
    a:hover { text-decoration: underline; }
    .desc { color: #666; font-size: 0.9em; margin-left: 0.5em; }
  </style>
</head>
<body>
  <h1>nexus API Documentation</h1>
  <ul>
    {{range .Services}}
    <li>
      <a href="{{.URL}}">{{.Name}}</a>
      <span class="desc">{{.Description}}</span>
    </li>
    {{end}}
  </ul>
</body>
</html>`))

// ServiceLink describes a service for the docs index page.
type ServiceLink struct {
	Name        string
	URL         string
	Description string
}

// DocsIndex serves an HTML index page linking to all service docs.
func DocsIndex(services []ServiceLink) http.HandlerFunc {
	return func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		if err := docsIndexTmpl.Execute(w, map[string]any{"Services": services}); err != nil {
			log.Printf("[gohttp] docs index template: %v", err)
		}
	}
}
