// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Jared Redh. All rights reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: hermit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-side monotonic timestamp in nanoseconds (for RTT calculation).
	ClientSendNs  int64 `protobuf:"varint,1,opt,name=client_send_ns,json=clientSendNs,proto3" json:"client_send_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_hermit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetClientSendNs() int64 {
	if x != nil {
		return x.ClientSendNs
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientSendNs  int64                  `protobuf:"varint,1,opt,name=client_send_ns,json=clientSendNs,proto3" json:"client_send_ns,omitempty"`
	ServerRecvNs  int64                  `protobuf:"varint,2,opt,name=server_recv_ns,json=serverRecvNs,proto3" json:"server_recv_ns,omitempty"`
	ServerSendNs  int64                  `protobuf:"varint,3,opt,name=server_send_ns,json=serverSendNs,proto3" json:"server_send_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_hermit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetClientSendNs() int64 {
	if x != nil {
		return x.ClientSendNs
	}
	return 0
}

func (x *PingResponse) GetServerRecvNs() int64 {
	if x != nil {
		return x.ServerRecvNs
	}
	return 0
}

func (x *PingResponse) GetServerSendNs() int64 {
	if x != nil {
		return x.ServerSendNs
	}
	return 0
}

type BenchmarkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of sequential pings to run server-side for statistical measurement.
	Iterations uint32 `protobuf:"varint,1,opt,name=iterations,proto3" json:"iterations,omitempty"`
	// Payload size in bytes for bandwidth testing (0 = latency-only).
	PayloadBytes  uint32 `protobuf:"varint,2,opt,name=payload_bytes,json=payloadBytes,proto3" json:"payload_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BenchmarkRequest) Reset() {
	*x = BenchmarkRequest{}
	mi := &file_hermit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenchmarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenchmarkRequest) ProtoMessage() {}

func (x *BenchmarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenchmarkRequest.ProtoReflect.Descriptor instead.
func (*BenchmarkRequest) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{2}
}

func (x *BenchmarkRequest) GetIterations() uint32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

func (x *BenchmarkRequest) GetPayloadBytes() uint32 {
	if x != nil {
		return x.PayloadBytes
	}
	return 0
}

type BenchmarkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-iteration timing in nanoseconds.
	LatenciesNs []int64 `protobuf:"varint,1,rep,packed,name=latencies_ns,json=latenciesNs,proto3" json:"latencies_ns,omitempty"`
	// Aggregate stats.
	MinNs  int64 `protobuf:"varint,2,opt,name=min_ns,json=minNs,proto3" json:"min_ns,omitempty"`
	MaxNs  int64 `protobuf:"varint,3,opt,name=max_ns,json=maxNs,proto3" json:"max_ns,omitempty"`
	MeanNs int64 `protobuf:"varint,4,opt,name=mean_ns,json=meanNs,proto3" json:"mean_ns,omitempty"`
	P50Ns  int64 `protobuf:"varint,5,opt,name=p50_ns,json=p50Ns,proto3" json:"p50_ns,omitempty"`
	P99Ns  int64 `protobuf:"varint,6,opt,name=p99_ns,json=p99Ns,proto3" json:"p99_ns,omitempty"`
	// Server-side processing overhead per iteration.
	ProcessingOverheadNs int64 `protobuf:"varint,7,opt,name=processing_overhead_ns,json=processingOverheadNs,proto3" json:"processing_overhead_ns,omitempty"`
	// Whether TLS was active on this connection.
	TlsActive     bool   `protobuf:"varint,8,opt,name=tls_active,json=tlsActive,proto3" json:"tls_active,omitempty"`
	TlsVersion    string `protobuf:"bytes,9,opt,name=tls_version,json=tlsVersion,proto3" json:"tls_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BenchmarkResponse) Reset() {
	*x = BenchmarkResponse{}
	mi := &file_hermit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenchmarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenchmarkResponse) ProtoMessage() {}

func (x *BenchmarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenchmarkResponse.ProtoReflect.Descriptor instead.
func (*BenchmarkResponse) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{3}
}

func (x *BenchmarkResponse) GetLatenciesNs() []int64 {
	if x != nil {
		return x.LatenciesNs
	}
	return nil
}

func (x *BenchmarkResponse) GetMinNs() int64 {
	if x != nil {
		return x.MinNs
	}
	return 0
}

func (x *BenchmarkResponse) GetMaxNs() int64 {
	if x != nil {
		return x.MaxNs
	}
	return 0
}

func (x *BenchmarkResponse) GetMeanNs() int64 {
	if x != nil {
		return x.MeanNs
	}
	return 0
}

func (x *BenchmarkResponse) GetP50Ns() int64 {
	if x != nil {
		return x.P50Ns
	}
	return 0
}

func (x *BenchmarkResponse) GetP99Ns() int64 {
	if x != nil {
		return x.P99Ns
	}
	return 0
}

func (x *BenchmarkResponse) GetProcessingOverheadNs() int64 {
	if x != nil {
		return x.ProcessingOverheadNs
	}
	return 0
}

func (x *BenchmarkResponse) GetTlsActive() bool {
	if x != nil {
		return x.TlsActive
	}
	return false
}

func (x *BenchmarkResponse) GetTlsVersion() string {
	if x != nil {
		return x.TlsVersion
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_hermit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_hermit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LoginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoRequest) Reset() {
	*x = ServerInfoRequest{}
	mi := &file_hermit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoRequest) ProtoMessage() {}

func (x *ServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoRequest.ProtoReflect.Descriptor instead.
func (*ServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{6}
}

type ServerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	RustVersion   string                 `protobuf:"bytes,5,opt,name=rust_version,json=rustVersion,proto3" json:"rust_version,omitempty"`
	TlsEnabled    bool                   `protobuf:"varint,6,opt,name=tls_enabled,json=tlsEnabled,proto3" json:"tls_enabled,omitempty"`
	GrpcPort      uint32                 `protobuf:"varint,7,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	TcpPort       uint32                 `protobuf:"varint,8,opt,name=tcp_port,json=tcpPort,proto3" json:"tcp_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoResponse) Reset() {
	*x = ServerInfoResponse{}
	mi := &file_hermit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoResponse) ProtoMessage() {}

func (x *ServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{7}
}

func (x *ServerInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfoResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ServerInfoResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ServerInfoResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ServerInfoResponse) GetRustVersion() string {
	if x != nil {
		return x.RustVersion
	}
	return ""
}

func (x *ServerInfoResponse) GetTlsEnabled() bool {
	if x != nil {
		return x.TlsEnabled
	}
	return false
}

func (x *ServerInfoResponse) GetGrpcPort() uint32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

func (x *ServerInfoResponse) GetTcpPort() uint32 {
	if x != nil {
		return x.TcpPort
	}
	return 0
}

type KvSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvSetRequest) Reset() {
	*x = KvSetRequest{}
	mi := &file_hermit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvSetRequest) ProtoMessage() {}

func (x *KvSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvSetRequest.ProtoReflect.Descriptor instead.
func (*KvSetRequest) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{8}
}

func (x *KvSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KvSetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type KvSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvSetResponse) Reset() {
	*x = KvSetResponse{}
	mi := &file_hermit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvSetResponse) ProtoMessage() {}

func (x *KvSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvSetResponse.ProtoReflect.Descriptor instead.
func (*KvSetResponse) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{9}
}

func (x *KvSetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *KvSetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type KvGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvGetRequest) Reset() {
	*x = KvGetRequest{}
	mi := &file_hermit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvGetRequest) ProtoMessage() {}

func (x *KvGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvGetRequest.ProtoReflect.Descriptor instead.
func (*KvGetRequest) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{10}
}

func (x *KvGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KvGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvGetResponse) Reset() {
	*x = KvGetResponse{}
	mi := &file_hermit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvGetResponse) ProtoMessage() {}

func (x *KvGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvGetResponse.ProtoReflect.Descriptor instead.
func (*KvGetResponse) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{11}
}

func (x *KvGetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *KvGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KvGetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type KvListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvListRequest) Reset() {
	*x = KvListRequest{}
	mi := &file_hermit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvListRequest) ProtoMessage() {}

func (x *KvListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvListRequest.ProtoReflect.Descriptor instead.
func (*KvListRequest) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{12}
}

type KvListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvListResponse) Reset() {
	*x = KvListResponse{}
	mi := &file_hermit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvListResponse) ProtoMessage() {}

func (x *KvListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvListResponse.ProtoReflect.Descriptor instead.
func (*KvListResponse) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{13}
}

func (x *KvListResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type SqlInsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlInsertRequest) Reset() {
	*x = SqlInsertRequest{}
	mi := &file_hermit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlInsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlInsertRequest) ProtoMessage() {}

func (x *SqlInsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlInsertRequest.ProtoReflect.Descriptor instead.
func (*SqlInsertRequest) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{14}
}

func (x *SqlInsertRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SqlInsertRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SqlInsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queued        bool                   `protobuf:"varint,1,opt,name=queued,proto3" json:"queued,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlInsertResponse) Reset() {
	*x = SqlInsertResponse{}
	mi := &file_hermit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlInsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlInsertResponse) ProtoMessage() {}

func (x *SqlInsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlInsertResponse.ProtoReflect.Descriptor instead.
func (*SqlInsertResponse) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{15}
}

func (x *SqlInsertResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

func (x *SqlInsertResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SqlQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If set, filter rows where key = this value. Empty = return all rows.
	KeyFilter string `protobuf:"bytes,1,opt,name=key_filter,json=keyFilter,proto3" json:"key_filter,omitempty"`
	// Max rows to return (0 = no limit).
	Limit         uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlQueryRequest) Reset() {
	*x = SqlQueryRequest{}
	mi := &file_hermit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlQueryRequest) ProtoMessage() {}

func (x *SqlQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlQueryRequest.ProtoReflect.Descriptor instead.
func (*SqlQueryRequest) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{16}
}

func (x *SqlQueryRequest) GetKeyFilter() string {
	if x != nil {
		return x.KeyFilter
	}
	return ""
}

func (x *SqlQueryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SqlRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAtMs   uint64                 `protobuf:"varint,4,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlRow) Reset() {
	*x = SqlRow{}
	mi := &file_hermit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlRow) ProtoMessage() {}

func (x *SqlRow) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlRow.ProtoReflect.Descriptor instead.
func (*SqlRow) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{17}
}

func (x *SqlRow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SqlRow) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SqlRow) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SqlRow) GetCreatedAtMs() uint64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

type SqlQueryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Rows           []*SqlRow              `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	TotalCommitted uint64                 `protobuf:"varint,2,opt,name=total_committed,json=totalCommitted,proto3" json:"total_committed,omitempty"`
	PendingWrites  uint64                 `protobuf:"varint,3,opt,name=pending_writes,json=pendingWrites,proto3" json:"pending_writes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SqlQueryResponse) Reset() {
	*x = SqlQueryResponse{}
	mi := &file_hermit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlQueryResponse) ProtoMessage() {}

func (x *SqlQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlQueryResponse.ProtoReflect.Descriptor instead.
func (*SqlQueryResponse) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{18}
}

func (x *SqlQueryResponse) GetRows() []*SqlRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *SqlQueryResponse) GetTotalCommitted() uint64 {
	if x != nil {
		return x.TotalCommitted
	}
	return 0
}

func (x *SqlQueryResponse) GetPendingWrites() uint64 {
	if x != nil {
		return x.PendingWrites
	}
	return 0
}

type DbStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbStatsRequest) Reset() {
	*x = DbStatsRequest{}
	mi := &file_hermit_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbStatsRequest) ProtoMessage() {}

func (x *DbStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbStatsRequest.ProtoReflect.Descriptor instead.
func (*DbStatsRequest) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{19}
}

type DbStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DocKeyCount        uint64                 `protobuf:"varint,1,opt,name=doc_key_count,json=docKeyCount,proto3" json:"doc_key_count,omitempty"`
	DocCompressedBytes uint64                 `protobuf:"varint,2,opt,name=doc_compressed_bytes,json=docCompressedBytes,proto3" json:"doc_compressed_bytes,omitempty"`
	RelRowCount        uint64                 `protobuf:"varint,3,opt,name=rel_row_count,json=relRowCount,proto3" json:"rel_row_count,omitempty"`
	RelPendingWrites   uint64                 `protobuf:"varint,4,opt,name=rel_pending_writes,json=relPendingWrites,proto3" json:"rel_pending_writes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DbStatsResponse) Reset() {
	*x = DbStatsResponse{}
	mi := &file_hermit_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbStatsResponse) ProtoMessage() {}

func (x *DbStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbStatsResponse.ProtoReflect.Descriptor instead.
func (*DbStatsResponse) Descriptor() ([]byte, []int) {
	return file_hermit_proto_rawDescGZIP(), []int{20}
}

func (x *DbStatsResponse) GetDocKeyCount() uint64 {
	if x != nil {
		return x.DocKeyCount
	}
	return 0
}

func (x *DbStatsResponse) GetDocCompressedBytes() uint64 {
	if x != nil {
		return x.DocCompressedBytes
	}
	return 0
}

func (x *DbStatsResponse) GetRelRowCount() uint64 {
	if x != nil {
		return x.RelRowCount
	}
	return 0
}

func (x *DbStatsResponse) GetRelPendingWrites() uint64 {
	if x != nil {
		return x.RelPendingWrites
	}
	return 0
}

var File_hermit_proto protoreflect.FileDescriptor

const file_hermit_proto_rawDesc = "" +
	"\n" +
	"\fhermit.proto\x12\x06hermit\x1a\x1fgoogle/protobuf/timestamp.proto\"3\n" +
	"\vPingRequest\x12$\n" +
	"\x0eclient_send_ns\x18\x01 \x01(\x03R\fclientSendNs\"\x80\x01\n" +
	"\fPingResponse\x12$\n" +
	"\x0eclient_send_ns\x18\x01 \x01(\x03R\fclientSendNs\x12$\n" +
	"\x0eserver_recv_ns\x18\x02 \x01(\x03R\fserverRecvNs\x12$\n" +
	"\x0eserver_send_ns\x18\x03 \x01(\x03R\fserverSendNs\"W\n" +
	"\x10BenchmarkRequest\x12\x1e\n" +
	"\n" +
	"iterations\x18\x01 \x01(\rR\n" +
	"iterations\x12#\n" +
	"\rpayload_bytes\x18\x02 \x01(\rR\fpayloadBytes\"\xa1\x02\n" +
	"\x11BenchmarkResponse\x12!\n" +
	"\flatencies_ns\x18\x01 \x03(\x03R\vlatenciesNs\x12\x15\n" +
	"\x06min_ns\x18\x02 \x01(\x03R\x05minNs\x12\x15\n" +
	"\x06max_ns\x18\x03 \x01(\x03R\x05maxNs\x12\x17\n" +
	"\amean_ns\x18\x04 \x01(\x03R\x06meanNs\x12\x15\n" +
	"\x06p50_ns\x18\x05 \x01(\x03R\x05p50Ns\x12\x15\n" +
	"\x06p99_ns\x18\x06 \x01(\x03R\x05p99Ns\x124\n" +
	"\x16processing_overhead_ns\x18\a \x01(\x03R\x14processingOverheadNs\x12\x1d\n" +
	"\n" +
	"tls_active\x18\b \x01(\bR\ttlsActive\x12\x1f\n" +
	"\vtls_version\x18\t \x01(\tR\n" +
	"tlsVersion\"@\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"^\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x13\n" +
	"\x11ServerInfoRequest\"\xa4\x02\n" +
	"\x12ServerInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\frust_version\x18\x05 \x01(\tR\vrustVersion\x12\x1f\n" +
	"\vtls_enabled\x18\x06 \x01(\bR\n" +
	"tlsEnabled\x12\x1b\n" +
	"\tgrpc_port\x18\a \x01(\rR\bgrpcPort\x12\x19\n" +
	"\btcp_port\x18\b \x01(\rR\atcpPort\"6\n" +
	"\fKvSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"5\n" +
	"\rKvSetResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\" \n" +
	"\fKvGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"Q\n" +
	"\rKvGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x0f\n" +
	"\rKvListRequest\"$\n" +
	"\x0eKvListResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\":\n" +
	"\x10SqlInsertRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"A\n" +
	"\x11SqlInsertResponse\x12\x16\n" +
	"\x06queued\x18\x01 \x01(\bR\x06queued\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"F\n" +
	"\x0fSqlQueryRequest\x12\x1d\n" +
	"\n" +
	"key_filter\x18\x01 \x01(\tR\tkeyFilter\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"d\n" +
	"\x06SqlRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\"\n" +
	"\rcreated_at_ms\x18\x04 \x01(\x04R\vcreatedAtMs\"\x86\x01\n" +
	"\x10SqlQueryResponse\x12\"\n" +
	"\x04rows\x18\x01 \x03(\v2\x0e.hermit.SqlRowR\x04rows\x12'\n" +
	"\x0ftotal_committed\x18\x02 \x01(\x04R\x0etotalCommitted\x12%\n" +
	"\x0epending_writes\x18\x03 \x01(\x04R\rpendingWrites\"\x10\n" +
	"\x0eDbStatsRequest\"\xb9\x01\n" +
	"\x0fDbStatsResponse\x12\"\n" +
	"\rdoc_key_count\x18\x01 \x01(\x04R\vdocKeyCount\x120\n" +
	"\x14doc_compressed_bytes\x18\x02 \x01(\x04R\x12docCompressedBytes\x12\"\n" +
	"\rrel_row_count\x18\x03 \x01(\x04R\vrelRowCount\x12,\n" +
	"\x12rel_pending_writes\x18\x04 \x01(\x04R\x10relPendingWrites2\xda\x04\n" +
	"\x06Hermit\x121\n" +
	"\x04Ping\x12\x13.hermit.PingRequest\x1a\x14.hermit.PingResponse\x12@\n" +
	"\tBenchmark\x12\x18.hermit.BenchmarkRequest\x1a\x19.hermit.BenchmarkResponse\x124\n" +
	"\x05Login\x12\x14.hermit.LoginRequest\x1a\x15.hermit.LoginResponse\x12C\n" +
	"\n" +
	"ServerInfo\x12\x19.hermit.ServerInfoRequest\x1a\x1a.hermit.ServerInfoResponse\x124\n" +
	"\x05KvSet\x12\x14.hermit.KvSetRequest\x1a\x15.hermit.KvSetResponse\x124\n" +
	"\x05KvGet\x12\x14.hermit.KvGetRequest\x1a\x15.hermit.KvGetResponse\x127\n" +
	"\x06KvList\x12\x15.hermit.KvListRequest\x1a\x16.hermit.KvListResponse\x12@\n" +
	"\tSqlInsert\x12\x18.hermit.SqlInsertRequest\x1a\x19.hermit.SqlInsertResponse\x12=\n" +
	"\bSqlQuery\x12\x17.hermit.SqlQueryRequest\x1a\x18.hermit.SqlQueryResponse\x12:\n" +
	"\aDbStats\x12\x16.hermit.DbStatsRequest\x1a\x17.hermit.DbStatsResponseB+Z)github.com/jredh-dev/hermit/cmd/tui/protob\x06proto3"

var (
	file_hermit_proto_rawDescOnce sync.Once
	file_hermit_proto_rawDescData []byte
)

func file_hermit_proto_rawDescGZIP() []byte {
	file_hermit_proto_rawDescOnce.Do(func() {
		file_hermit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hermit_proto_rawDesc), len(file_hermit_proto_rawDesc)))
	})
	return file_hermit_proto_rawDescData
}

var file_hermit_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_hermit_proto_goTypes = []any{
	(*PingRequest)(nil),           // 0: hermit.PingRequest
	(*PingResponse)(nil),          // 1: hermit.PingResponse
	(*BenchmarkRequest)(nil),      // 2: hermit.BenchmarkRequest
	(*BenchmarkResponse)(nil),     // 3: hermit.BenchmarkResponse
	(*LoginRequest)(nil),          // 4: hermit.LoginRequest
	(*LoginResponse)(nil),         // 5: hermit.LoginResponse
	(*ServerInfoRequest)(nil),     // 6: hermit.ServerInfoRequest
	(*ServerInfoResponse)(nil),    // 7: hermit.ServerInfoResponse
	(*KvSetRequest)(nil),          // 8: hermit.KvSetRequest
	(*KvSetResponse)(nil),         // 9: hermit.KvSetResponse
	(*KvGetRequest)(nil),          // 10: hermit.KvGetRequest
	(*KvGetResponse)(nil),         // 11: hermit.KvGetResponse
	(*KvListRequest)(nil),         // 12: hermit.KvListRequest
	(*KvListResponse)(nil),        // 13: hermit.KvListResponse
	(*SqlInsertRequest)(nil),      // 14: hermit.SqlInsertRequest
	(*SqlInsertResponse)(nil),     // 15: hermit.SqlInsertResponse
	(*SqlQueryRequest)(nil),       // 16: hermit.SqlQueryRequest
	(*SqlRow)(nil),                // 17: hermit.SqlRow
	(*SqlQueryResponse)(nil),      // 18: hermit.SqlQueryResponse
	(*DbStatsRequest)(nil),        // 19: hermit.DbStatsRequest
	(*DbStatsResponse)(nil),       // 20: hermit.DbStatsResponse
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_hermit_proto_depIdxs = []int32{
	21, // 0: hermit.ServerInfoResponse.started_at:type_name -> google.protobuf.Timestamp
	17, // 1: hermit.SqlQueryResponse.rows:type_name -> hermit.SqlRow
	0,  // 2: hermit.Hermit.Ping:input_type -> hermit.PingRequest
	2,  // 3: hermit.Hermit.Benchmark:input_type -> hermit.BenchmarkRequest
	4,  // 4: hermit.Hermit.Login:input_type -> hermit.LoginRequest
	6,  // 5: hermit.Hermit.ServerInfo:input_type -> hermit.ServerInfoRequest
	8,  // 6: hermit.Hermit.KvSet:input_type -> hermit.KvSetRequest
	10, // 7: hermit.Hermit.KvGet:input_type -> hermit.KvGetRequest
	12, // 8: hermit.Hermit.KvList:input_type -> hermit.KvListRequest
	14, // 9: hermit.Hermit.SqlInsert:input_type -> hermit.SqlInsertRequest
	16, // 10: hermit.Hermit.SqlQuery:input_type -> hermit.SqlQueryRequest
	19, // 11: hermit.Hermit.DbStats:input_type -> hermit.DbStatsRequest
	1,  // 12: hermit.Hermit.Ping:output_type -> hermit.PingResponse
	3,  // 13: hermit.Hermit.Benchmark:output_type -> hermit.BenchmarkResponse
	5,  // 14: hermit.Hermit.Login:output_type -> hermit.LoginResponse
	7,  // 15: hermit.Hermit.ServerInfo:output_type -> hermit.ServerInfoResponse
	9,  // 16: hermit.Hermit.KvSet:output_type -> hermit.KvSetResponse
	11, // 17: hermit.Hermit.KvGet:output_type -> hermit.KvGetResponse
	13, // 18: hermit.Hermit.KvList:output_type -> hermit.KvListResponse
	15, // 19: hermit.Hermit.SqlInsert:output_type -> hermit.SqlInsertResponse
	18, // 20: hermit.Hermit.SqlQuery:output_type -> hermit.SqlQueryResponse
	20, // 21: hermit.Hermit.DbStats:output_type -> hermit.DbStatsResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_hermit_proto_init() }
func file_hermit_proto_init() {
	if File_hermit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hermit_proto_rawDesc), len(file_hermit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hermit_proto_goTypes,
		DependencyIndexes: file_hermit_proto_depIdxs,
		MessageInfos:      file_hermit_proto_msgTypes,
	}.Build()
	File_hermit_proto = out.File
	file_hermit_proto_goTypes = nil
	file_hermit_proto_depIdxs = nil
}
