// Command server runs the discord-monitor HTTP server.
//
// It connects to PostgreSQL (running migrations on startup), optionally
// initializes a selfbot client and scanner for Discord user API access,
// and serves the monitoring HTTP API.
//
// Environment variables:
//
//	PORT                     HTTP listen port (default: "8080")
//	DATABASE_URL             PostgreSQL connection string
//	                         (default: "host=/tmp/ctl-pg dbname=discord_monitor user=jredh")
//	DISCORD_SELFBOT_TOKEN    Discord user token for selfbot mode (optional)
//	SCAN_INTERVAL_SELFBOT    Polling interval for selfbot scanner (default: "60s")
//
// Flags:
//
//	--port    HTTP listen port (overrides PORT env)
//	--db      PostgreSQL connection string (overrides DATABASE_URL env)
//	--docs    Enable Swagger UI at /docs (local dev only)
//	--help, -h, -?    Print usage and exit
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//	@title          nexus-discord-monitor API
//	@version        1.0
//	@description    Discord monitoring service with selfbot scanning, keyword watchlists, priority scoring, digests, and activity heatmaps.
//	@host           localhost:8080
//	@BasePath       /

package main

import (
	"context"
	_ "embed"
	"flag"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/jredh-dev/nexus/services/discord-monitor/internal/database"
	"github.com/jredh-dev/nexus/services/discord-monitor/internal/selfbot"
	"github.com/jredh-dev/nexus/services/discord-monitor/internal/server"
	gohttp "github.com/jredh-dev/nexus/services/go-http"
)

// swaggerSpec embeds the generated swagger.json so the binary is self-contained.
// Generated by: swag init --v2 --generalInfo services/discord-monitor/cmd/server/main.go --output services/discord-monitor/cmd/server/docs
//
//go:embed docs/swagger.json
var swaggerSpec []byte

func main() {
	os.Exit(run())
}

func run() int {
	fs := flag.NewFlagSet("discord-monitor", flag.ContinueOnError)
	portFlag := fs.String("port", "", "HTTP listen port (overrides PORT env)")
	dbFlag := fs.String("db", "", "PostgreSQL connection string (overrides DATABASE_URL env)")
	enableDocs := fs.Bool("docs", false, "Enable Swagger UI at /docs (local dev only)")

	// Check for help flags before parsing to handle -? which flag doesn't
	// support natively.
	if len(os.Args) > 1 {
		arg := os.Args[1]
		if arg == "--help" || arg == "-h" || arg == "-?" || arg == "help" {
			fs.Usage()
			return 0
		}
	}

	if err := fs.Parse(os.Args[1:]); err != nil {
		return 1
	}

	// Resolve config: flag > env > default.
	port := resolve(*portFlag, os.Getenv("PORT"), "8080")
	dbURL := resolve(*dbFlag, os.Getenv("DATABASE_URL"), "host=/tmp/ctl-pg dbname=discord_monitor user=jredh")
	selfbotToken := os.Getenv("DISCORD_SELFBOT_TOKEN")
	scanInterval := parseDuration(os.Getenv("SCAN_INTERVAL_SELFBOT"), 60*time.Second)

	log.Printf("[discord-monitor] starting: port=%s db_configured=true selfbot=%v scan_interval=%s",
		port, selfbotToken != "", scanInterval)

	// Create a root context that is cancelled on SIGINT/SIGTERM.
	// This context is used by the scanner goroutine for graceful shutdown.
	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer cancel()

	// Connect to PostgreSQL and run migrations.
	dbCtx, dbCancel := context.WithTimeout(ctx, 15*time.Second)
	defer dbCancel()

	db, err := database.New(dbCtx, dbURL)
	if err != nil {
		log.Fatalf("[discord-monitor] database: %v", err)
	}
	defer db.Close()
	log.Println("[discord-monitor] database connected, migrations applied")

	// Track selfbot state for the server config.
	selfbotConnected := false
	userID := ""

	// Optionally initialize selfbot client, verify token, and start scanner.
	if selfbotToken != "" {
		client := selfbot.New(selfbotToken)

		// Validate the token by calling GetMe. This also gives us the
		// user ID which we need for priority scoring (mention detection).
		verifyCtx, verifyCancel := context.WithTimeout(ctx, 10*time.Second)
		user, err := client.GetMe(verifyCtx)
		verifyCancel()

		if err != nil {
			log.Printf("[discord-monitor] selfbot token validation failed: %v", err)
			log.Println("[discord-monitor] continuing without selfbot — API-only mode")
		} else {
			selfbotConnected = true
			userID = user.ID
			log.Printf("[discord-monitor] selfbot authenticated as %s#%s (%s)",
				user.Username, user.Discriminator, user.ID)

			// Start the scanner goroutine. It will run until ctx is cancelled
			// (SIGINT/SIGTERM). The scanner performs periodic guild/channel/message
			// sync from Discord.
			scanner := selfbot.NewScanner(client, db, scanInterval)
			go scanner.Start(ctx)
			log.Printf("[discord-monitor] scanner started, interval=%s", scanInterval)
		}
	}

	// Build and start the HTTP server. The server gets the userID for
	// priority scoring in the /api/unread endpoint.
	srv := server.New(server.Config{
		DB:               db,
		SelfbotConnected: selfbotConnected,
		UserID:           userID,
	})

	// Mount Swagger UI if --docs flag is set (local dev only).
	if *enableDocs {
		gohttp.EnableDocs(srv.Router, swaggerSpec)
	}

	srv.OnStop(func() {
		log.Println("[discord-monitor] shutting down...")
		// Cancel the root context to stop the scanner goroutine.
		cancel()
		log.Println("[discord-monitor] closing database connection")
		db.Close()
	})

	log.Printf("[discord-monitor] listening on :%s", port)
	if err := srv.ListenAndServe(":" + port); err != nil {
		log.Fatalf("[discord-monitor] server: %v", err)
	}

	return 0
}

// resolve returns the first non-empty string from the arguments.
// Used for flag > env > default priority.
func resolve(values ...string) string {
	for _, v := range values {
		if v != "" {
			return v
		}
	}
	return ""
}

// parseDuration parses a duration string, returning fallback on error or
// empty input. Supports Go duration strings like "30s", "5m", "1h".
func parseDuration(s string, fallback time.Duration) time.Duration {
	if s == "" {
		return fallback
	}
	d, err := time.ParseDuration(s)
	if err != nil {
		log.Printf("[discord-monitor] invalid duration %q, using default %s", s, fallback)
		return fallback
	}
	return d
}
