name: CI

on:
  push:
    branches: [main, 'workstream_**']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24-bookworm
      options: --add-host=gitea:host-gateway
    steps:
      - name: Install git
        run: apt-get update -qq && apt-get install -y -qq git >/dev/null 2>&1

      - name: Checkout
        run: |
          git clone --depth=1 --branch="${GITHUB_REF_NAME}" "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git" .
          git checkout "${GITHUB_SHA}"

      - name: Download dependencies
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -count=1 -timeout 120s

      - name: Build portal
        run: go build -o bin/portal ./services/portal/cmd/server/

      - name: Build cal
        run: go build -o bin/cal ./services/cal/cmd/server/

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    container:
      image: docker:cli
      options: --add-host=gitea:host-gateway
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Install git
        run: apk add --no-cache git >/dev/null 2>&1

      - name: Checkout
        run: |
          git clone --depth=1 --branch="${GITHUB_REF_NAME}" "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git" src
          cd src && git checkout "${GITHUB_SHA}"

      - name: Build portal image
        run: |
          docker build \
            -t nexus-portal-ci:${GITHUB_SHA::8} \
            -f services/portal/Dockerfile \
            .
        working-directory: src

      - name: Run portal container
        run: |
          docker run -d \
            --name nexus-portal-ci \
            --network agentic-network \
            -e PORT=8080 \
            -e ENV=test \
            -e DB_PATH=/app/data/test.db \
            -e SESSION_SECRET=ci-integration-test-secret \
            nexus-portal-ci:${GITHUB_SHA::8}

      - name: Wait for healthy
        run: |
          echo "Waiting for portal to be ready..."
          for i in $(seq 1 30); do
            if wget -q -O /dev/null http://nexus-portal-ci:8080/health 2>/dev/null; then
              echo "Portal healthy after ${i}s"
              exit 0
            fi
            sleep 1
          done
          echo "FAIL: portal not healthy after 30s"
          docker logs nexus-portal-ci 2>&1 || true
          exit 1

      - name: Test endpoints
        run: |
          PASS=0
          FAIL=0
          BASE="http://nexus-portal-ci:8080"

          check() {
            desc="$1"; url="$2"; expect="$3"
            status=$(wget --server-response -O /dev/null "$url" 2>&1 | awk '/^  HTTP/{print $2}' | tail -1) || true
            if [ "$status" = "$expect" ]; then
              echo "PASS: $desc (HTTP $status)"
              PASS=$((PASS + 1))
            else
              echo "FAIL: $desc — got HTTP ${status:-timeout}, want $expect"
              FAIL=$((FAIL + 1))
            fi
          }

          check "GET /health"    "$BASE/health"    "200"
          check "GET /"          "$BASE/"           "200"
          check "GET /login"     "$BASE/login"      "200"
          check "GET /signup"    "$BASE/signup"     "200"

          # POST signup — should redirect (302 or 303)
          signup_status=$(wget --server-response --max-redirect=0 \
            --post-data "username=ciuser&email=ci@test.com&phone=5550001234&password=testpass&name=CI+User" \
            -O /dev/null "$BASE/signup" 2>&1 | awk '/^  HTTP/{print $2}' | head -1) || true
          case "$signup_status" in
            302|303)
              echo "PASS: POST /signup redirects (HTTP $signup_status)"
              PASS=$((PASS + 1)) ;;
            *)
              echo "FAIL: POST /signup — got HTTP ${signup_status:-timeout}, want 302 or 303"
              FAIL=$((FAIL + 1)) ;;
          esac

          # /dashboard without auth should redirect (302)
          dash_status=$(wget --server-response --max-redirect=0 \
            -O /dev/null "$BASE/dashboard" 2>&1 | awk '/^  HTTP/{print $2}' | head -1) || true
          case "$dash_status" in
            302|303)
              echo "PASS: GET /dashboard redirects without auth (HTTP $dash_status)"
              PASS=$((PASS + 1)) ;;
            *)
              echo "FAIL: GET /dashboard — got HTTP ${dash_status:-timeout}, want 302 or 303"
              FAIL=$((FAIL + 1)) ;;
          esac

          echo ""
          echo "=== Results: $PASS passed, $FAIL failed ==="
          [ "$FAIL" -eq 0 ]

      - name: Cleanup
        if: always()
        run: |
          docker rm -f nexus-portal-ci 2>/dev/null || true
          docker rmi -f nexus-portal-ci:${GITHUB_SHA::8} 2>/dev/null || true
