name: CI

on:
  push:
    branches: [main, 'workstream_**']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24-bookworm
    steps:
      - name: Install git
        run: apt-get update -qq && apt-get install -y -qq git >/dev/null 2>&1

      - name: Checkout
        run: |
          git clone --depth=1 --branch="${GITHUB_REF_NAME}" "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git" .
          git checkout "${GITHUB_SHA}"

      - name: Download dependencies
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -count=1 -timeout 120s

      - name: Build portal
        run: go build -o bin/portal ./services/portal/cmd/server/

      - name: Build cal
        run: go build -o bin/cal ./services/cal/cmd/server/
