name: CI

on:
  push:
    branches: [main, 'workstream_**']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24-bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download dependencies
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -count=1 -timeout 120s

      - name: Build portal
        run: go build -o bin/portal ./services/portal/cmd/server/

      - name: Build cal
        run: go build -o bin/cal ./services/cal/cmd/server/
