// gatus-config-gen generates a Gatus config.yaml by querying the Docker socket
// for containers labelled nexus.monitor=true, then writes the result to stdout
// or a file. Runs once (for one-shot use) or loops on an interval (for sidecar use).
//
// Usage:
//
//	gatus-config-gen [--out /path/to/config.yaml] [--interval 60s]
//
// Docker labels consumed (all on containers with nexus.monitor=true):
//
//	nexus.group        — "app", "infra", "cloud" (default: "app")
//	nexus.description  — human description (unused by Gatus, logged)
//	nexus.health_url   — full URL or tcp://host:port to probe
//	nexus.health_type  — "http", "tcp", "none" (default: "http")
//
// Environment variables:
//
//	DISCORD_WEBHOOK_URL  — injected by Vault Agent; included in alerting block
//	DOCKER_HOST          — Docker socket (default: unix:///var/run/docker.sock)
//	GATUS_INTERVAL       — probe interval (default: 60s)
//	GATUS_STORAGE_PATH   — SQLite path for Gatus (default: /data/gatus.db)
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"sort"
	"strings"
	"text/template"
	"time"
)

// containerInfo is a minimal Docker API response shape.
type containerInfo struct {
	Names  []string          `json:"Names"`
	Labels map[string]string `json:"Labels"`
	State  string            `json:"State"`
}

// endpoint represents one Gatus endpoint entry.
type endpoint struct {
	Name       string
	Group      string
	URL        string
	HealthType string // "http", "tcp", "none"
	Interval   string
	HasAlert   bool
}

const gatusTmpl = `# gatus config.yaml — generated by gatus-config-gen
# DO NOT EDIT — this file is overwritten on every run.
# Add nexus.* labels to your docker-compose services to appear here.

storage:
  type: sqlite
  path: {{ .StoragePath }}

alerting:
{{ if .DiscordWebhook }}  discord:
    webhook-url: "{{ .DiscordWebhook }}"
    default-alert:
      enabled: true
      failure-threshold: 3
      success-threshold: 2
      send-on-resolved: true
{{ else }}  # DISCORD_WEBHOOK_URL not set — Discord alerting disabled
{{ end }}
endpoints:
{{ range .Groups }}  # ================================================================
  # {{ .Name }}
  # ================================================================
{{ range .Endpoints }}{{ if ne .HealthType "none" }}  - name: {{ .Name }}
    group: {{ .Group }}
    url: "{{ .URL }}"
    interval: {{ .Interval }}
    conditions:
{{ if eq .HealthType "tcp" }}      - "[CONNECTED] == true"
{{ else }}      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
{{ end }}{{ if .HasAlert }}    alerts:
      - type: discord
        enabled: true
        failure-threshold: 2
        send-on-resolved: true
{{ end }}{{ end }}{{ end }}{{ end }}
  # ================================================================
  # cloud domains
  # ================================================================

  - name: cal.jredh.com
    group: domains
    url: "https://cal.jredh.com/health"
    interval: 300s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2500"
      - "[CERTIFICATE_EXPIRATION] > 168h"

  - name: deadman.jredh.com
    group: domains
    url: "https://deadman.jredh.com/health"
    interval: 300s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2500"
      - "[CERTIFICATE_EXPIRATION] > 168h"
    alerts:
      - type: discord
        enabled: true
        failure-threshold: 2
        send-on-resolved: true
        description: "deadman.jredh.com cert or domain routing is down"

  - name: portal.jredh.com
    group: domains
    url: "https://portal.jredh.com/"
    interval: 300s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2500"
      - "[CERTIFICATE_EXPIRATION] > 168h"

  - name: secrets.jredh.com
    group: domains
    url: "https://nexus-secrets-dev-64739231665.us-central1.run.app/health"
    interval: 300s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2500"
`

type group struct {
	Name      string
	Endpoints []endpoint
}

type tmplData struct {
	StoragePath    string
	DiscordWebhook string
	Groups         []group
}

func main() {
	outPath := flag.String("out", "", "output file path (default: stdout)")
	interval := flag.Duration("interval", 0, "re-generate interval (0 = run once)")
	flag.Parse()

	// Support -h / -? in addition to --help.
	for _, arg := range os.Args[1:] {
		if arg == "-h" || arg == "-?" || arg == "help" {
			flag.Usage()
			os.Exit(0)
		}
	}

	run := func() {
		if err := generate(*outPath); err != nil {
			log.Printf("gatus-config-gen: generate failed: %v", err)
		}
	}

	run()
	if *interval > 0 {
		t := time.NewTicker(*interval)
		defer t.Stop()
		for range t.C {
			run()
		}
	}
}

func generate(outPath string) error {
	containers, err := listContainers()
	if err != nil {
		return fmt.Errorf("docker list: %w", err)
	}

	// Collect endpoints grouped by nexus.group.
	groupMap := map[string][]endpoint{}
	for _, c := range containers {
		if c.Labels["nexus.monitor"] != "true" {
			continue
		}
		name := containerName(c)
		healthType := labelOr(c.Labels, "nexus.health_type", "http")
		if healthType == "none" {
			// Watcher-style: no HTTP endpoint, nothing to probe.
			log.Printf("gatus-config-gen: skipping %s (health_type=none)", name)
			continue
		}
		healthURL := c.Labels["nexus.health_url"]
		if healthURL == "" {
			log.Printf("gatus-config-gen: skipping %s (no nexus.health_url)", name)
			continue
		}
		grp := labelOr(c.Labels, "nexus.group", "app")
		ep := endpoint{
			Name:       name,
			Group:      grp,
			URL:        healthURL,
			HealthType: healthType,
			Interval:   getEnv("GATUS_INTERVAL", "60s"),
			// Enable Discord alerts for app-group services (not pure infra).
			HasAlert: grp == "app",
		}
		groupMap[grp] = append(groupMap[grp], ep)
	}

	// Stable group order: app, infra, then anything else alphabetically.
	order := []string{"app", "infra"}
	for k := range groupMap {
		found := false
		for _, o := range order {
			if o == k {
				found = true
				break
			}
		}
		if !found {
			order = append(order, k)
		}
	}
	sort.Slice(order[2:], func(i, j int) bool { return order[i+2] < order[j+2] })

	var groups []group
	for _, grpName := range order {
		eps, ok := groupMap[grpName]
		if !ok {
			continue
		}
		sort.Slice(eps, func(i, j int) bool { return eps[i].Name < eps[j].Name })
		groups = append(groups, group{Name: grpName, Endpoints: eps})
	}

	data := tmplData{
		StoragePath:    getEnv("GATUS_STORAGE_PATH", "/data/gatus.db"),
		DiscordWebhook: os.Getenv("DISCORD_WEBHOOK_URL"),
		Groups:         groups,
	}

	t, err := template.New("gatus").Parse(gatusTmpl)
	if err != nil {
		return fmt.Errorf("template parse: %w", err)
	}

	var w *os.File
	if outPath == "" {
		w = os.Stdout
	} else {
		// Write to a temp file then rename — atomic so Gatus never reads a partial file.
		tmp := outPath + ".tmp"
		w, err = os.Create(tmp)
		if err != nil {
			return fmt.Errorf("create temp file: %w", err)
		}
		defer func() {
			w.Close()
			if err2 := os.Rename(tmp, outPath); err2 != nil {
				log.Printf("gatus-config-gen: rename failed: %v", err2)
			} else {
				log.Printf("gatus-config-gen: wrote %s (%d endpoints across %d groups)",
					outPath, totalEndpoints(groups), len(groups))
			}
		}()
	}

	return t.Execute(w, data)
}

// listContainers calls the Docker API via the Unix socket.
func listContainers() ([]containerInfo, error) {
	sock := getEnv("DOCKER_HOST", "unix:///var/run/docker.sock")
	sock = strings.TrimPrefix(sock, "unix://")

	transport := &http.Transport{
		DialContext: func(ctx context.Context, _, _ string) (net.Conn, error) {
			return (&net.Dialer{Timeout: 5 * time.Second}).DialContext(ctx, "unix", sock)
		},
	}
	client := &http.Client{Transport: transport, Timeout: 10 * time.Second}

	resp, err := client.Get("http://localhost/containers/json?all=false")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var containers []containerInfo
	if err := json.NewDecoder(resp.Body).Decode(&containers); err != nil {
		return nil, err
	}
	return containers, nil
}

// containerName strips the leading "/" from Docker container names.
func containerName(c containerInfo) string {
	if len(c.Names) == 0 {
		return "unknown"
	}
	name := strings.TrimPrefix(c.Names[0], "/")
	// Strip "agentic-" prefix used by this stack's container_name convention.
	name = strings.TrimPrefix(name, "agentic-")
	return name
}

func labelOr(labels map[string]string, key, def string) string {
	if v, ok := labels[key]; ok && v != "" {
		return v
	}
	return def
}

func getEnv(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func totalEndpoints(groups []group) int {
	n := 0
	for _, g := range groups {
		n += len(g.Endpoints)
	}
	return n
}
