// nexus-secrets - count-based secret admission service
// Copyright (C) 2026  nexus contributors
//
// Deploy notifications wired: 2026-03-04
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

//	@title          nexus-secrets API
//	@version        1.0
//	@description    Count-based secret admission service. Submit secrets and discover equivalence.
//	@host           localhost:8081
//	@BasePath       /

package main

import (
	_ "embed"
	"flag"
	"fmt"
	"log"
	"os"

	gohttp "github.com/jredh-dev/nexus/services/go-http"
	"github.com/jredh-dev/nexus/services/go-http/config"
	"github.com/jredh-dev/nexus/services/secrets/internal/handlers"
	"github.com/jredh-dev/nexus/services/secrets/internal/store"
)

// swaggerSpec embeds the generated swagger.json so the binary is self-contained.
// Generated by: swag init --v2 --generalInfo services/secrets/cmd/server/main.go --output services/secrets/cmd/server/docs
//
//go:embed docs/swagger.json
var swaggerSpec []byte

var (
	version   = "dev"
	commit    = "unknown"
	buildDate = "unknown"
)

func main() {
	showVersion := flag.Bool("version", false, "Show version information")
	enableDocs := flag.Bool("docs", false, "Enable Swagger UI at /docs (local dev only)")
	flag.Parse()

	if *showVersion {
		fmt.Printf("nexus-secrets %s\n", version)
		fmt.Printf("Commit: %s\n", commit)
		fmt.Printf("Built: %s\n", buildDate)
		os.Exit(0)
	}

	cfg := config.Load()
	s := store.New()
	h := handlers.New(s)

	srv := gohttp.New()
	srv.OnStop(h.Stop)

	// The riddle — start here
	srv.Router.Get("/", h.Riddle)
	srv.Router.Get("/api/riddle", h.Riddle)

	// Secrets API
	srv.Router.Post("/api/secrets", h.Submit)
	srv.Router.Get("/api/secrets", h.List)
	srv.Router.Get("/api/secrets/{id}", h.Get)
	srv.Router.Get("/api/stats", h.Stats)
	srv.Router.Get("/api/exposed", h.Exposed)

	// Mount Swagger UI if --docs flag is set (local dev only).
	if *enableDocs {
		gohttp.EnableDocs(srv.Router, swaggerSpec)
	}

	addr := ":" + cfg.Port
	log.Printf("nexus-secrets starting on %s", addr)
	log.Printf("  Riddle:  http://localhost%s/", addr)
	log.Printf("  API:     http://localhost%s/api/", addr)

	if err := srv.ListenAndServe(addr); err != nil {
		log.Fatalf("Server error: %v", err)
	}
}
